CREATE TABLE "user"(
	id_user SERIAL NOT NULL CONSTRAINT user_pkey PRIMARY KEY,
	username CHARACTER VARYING(100) NOT NULL CONSTRAINT user_ukey UNIQUE,
	person_name CHARACTER VARYING(60) NOT NULL,
	pass CHARACTER VARYING(32) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE
) with(
oids=false
);
