CREATE TABLE category(
	id_category SERIAL NOT NULL CONSTRAINT category_pkey PRIMARY KEY,
	category CHARACTER VARYING(50) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	color CHARACTER VARYING(6) NOT NULL,
	id_user INT NOT NULL CONSTRAINT category_user_fkey REFERENCES "user"(id_user) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT
) WITH(
OIDS=false
);
