CREATE TABLE article(
	id_article BIGSERIAL NOT NULL CONSTRAINT article_pkey PRIMARY KEY,
	title CHARACTER VARYING(150) NOT NULL,
	cover_path CHARACTER VARYING(100) NOT NULL,
	id_category INT NOT NULL CONSTRAINT article_category_fkey REFERENCES category(id_category) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT,
	article TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	id_user INT NOT NULL CONSTRAINT article_user_fkey REFERENCES "user"(id_user) MATCH SIMPLE ON UPDATE CASCADE ON DELETE RESTRICT
) WITH(
oids=false
);
